version: "3"
services:
  db: 
    image: mysql:5.7 # 사용할 이미지
    container_name: node-mysql
    ports:
      - 3306:3306 
    environment: # -e 옵션
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nodejs
      # MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      #POSTGRES_INITDB_ARGS: --encoding=UTF-8
    # command: # 명령어 실행
    #   - --character-set-server=utf8mb4
    #   - --collation-server=utf8mb4_unicode_ci
    # volumes:
    #   - /Users/jmlim/datadir:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)

  adminer:
    image: adminer
    container_name: node-adminer
    # restart: always
    ports:
      - 9000:8080